#' Predict if a file was generated by AI
#'
#' @param file file(s) to upload. Up to 5.
#'
#' @return TODO
#' @export
#'
#' @examplesIf GPTZeroR::gptzero_has_key()
#' # Requires API Key
#' gptzero_predict_file() #TODO
gptzero_predict_file <- function(file) {

  # TODO check file input

  f_l <- lapply(file, curl::form_file)

  req <- httr2::request(base_url = api_url()) |>
    httr2::req_headers(`X-API-KEY` = gptzero_get_key()) |>
    httr2::req_body_multipart(
      files = file
    )

  out <- req |>
    httr2::req_perform() |>
    httr2::resp_body_json()

  # TODO process output

}

#' Predict if text was generated by AI
#'
#' @param text text to upload
#'
#' @return TODO
#' @export
#'
#' @examplesIf GPTZeroR::has_gptzero_key()
#' # Requires API Key
#' gptzero_predict_text() #TODO
gptzero_predict_text <- function(text) {

  # TODO check text input

  req <- httr2::request(base_url = api_url()) |>
    httr2::req_headers(`X-API-KEY` = gptzero_get_key()) |>
    httr2::req_body_json(
      data = list(
        document = text
      )
    )

  out <- req |>
    httr2::req_perform() |>
    httr2::resp_body_json()

  # TODO process output

}
