#' Predict if a file was generated by AI
#'
#' @param file file(s) to upload. Up to 5.
#'
#' @return TODO
#' @export
#'
#' @examplesIf gptzeror::gptzero_has_key()
#' # Requires API Key
#' gptzero_predict_file() #TODO
gptzero_predict_file <- function(file) {

  # TODO check file input

  f_l <- lapply(file, curl::form_file)

  req <- httr2::request(base_url = api_url()) |>
    httr2::req_url_path_append('files') |>
    httr2::req_headers(
      `X-Api-Key` = gptzero_get_key(),
      accept = 'application/json'
    ) |>
    httr2::req_body_multipart(
      files = file
    )

  out <- req |>
    httr2::req_perform() |>
    httr2::resp_body_json()

  # TODO process output

  out
}

#' Predict if text was generated by AI
#'
#' @param text text to upload
#'
#' @return a tibble of sentence-level assessments
#' @export
#'
#' @examplesIf gptzeror::has_gptzero_key()
#' # Requires API Key
#' abstr <- 'Congressional district lines in many U.S. states are drawn by partisan
#' actors, raising concerns about gerrymandering. To separate the partisan effects
#' of redistricting from the effects of other factors including geography and
#' redistricting rules, we compare possible party compositions of the U.S. House
#' under the enacted plan to those under a set of alternative simulated plans
#' that serve as a non-partisan baseline. We find that partisan gerrymandering
#' is widespread in the 2020 redistricting cycle, but most of the electoral bias
#' it creates cancels at the national level, giving Republicans two additional
#' seats on average. Geography and redistricting rules separately contribute a
#' moderate pro-Republican bias. Finally, we find that partisan gerrymandering
#' reduces electoral competition and makes the partisan composition of the U.S. House
#' less responsive to shifts in the national vote.'
#'
#' abstr <- gsub('\\n', ' ', abstr) # remove the \n created by this multiline object
#'
#' gptzero_predict_text(abstr)
gptzero_predict_text <- function(text) {

  # check text input
  if (!is.character(text)) {
    cli::cli_abort('{.arg text} must be a character vector.')
  }
  if (length(text) != 1) {
    cli::cli_abort(
      c(
        '{.arg text} must be length 1.',
        'Iterate over {.fn gptzero_predict_text} for multiple requests.'
      )
    )
  }

  # formulate and perform request
  req <- httr2::request(base_url = api_url()) |>
    httr2::req_url_path_append('text') |>
    httr2::req_headers(
      `X-Api-Key` = gptzero_get_key(),
      accept = 'application/json'
    ) |>
    httr2::req_body_json(
      data = list(
        document = text
      )
    )

  out <- req |>
    httr2::req_perform() |>
    httr2::resp_body_json()

  process_doc(out)
}
